name: "[CD] Continuous Delivery"

# on:
# push:
# branches: [main]

on:
    pull_request:
        types: [opened, synchronize]

env:
    VERCEL_ORG_ID: vLXRukboV0xe34Jj8omhEpCT
    VERCEL_PROJECT_ID: prj_7boOEJYSV3AMoYS2nMZbIu3PdThi

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            ##===============
            - name: "Debug"
              run: "ls -la"
            - name: "Install Dependencies"
              run: "npm install"
            - name: "Vercel build"
              run: "npx vercel --prod --token=${{secrets.VERCEL_TOKEN}}"
